apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: globus-connect-data
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
