apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: globus-connect
spec:
  serviceName: globus-connect-service
  replicas: 1
  selector:
    matchLabels:
      k8s-app: globus-connect
  minReadySeconds: 10
  template:
    metadata:
      labels:
        k8s-app: globus-connect
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: globus-connect-server
        image: gitlab-registry.nrp-nautilus.io/prp/globus-connect:7f540862
        # image: gitlab-registry.nrp-nautilus.io/prp/globus-connect
        resources:
          limits:
            memory: 1Gi
            cpu: 1
          requests:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 80
          name: web
        imagePullPolicy: Always
        args: ['/bin/bash', '-c', 'su - gridftp -c "cd /home/gridftp && chmod 744 /home/gridftp/globus-connect-personal.sh && /home/gridftp/globus-connect-personal.sh"']
        volumeMounts:
            - mountPath: /data
              name: globus-connect-data
      volumes:
      - name: globus-connect-data
        persistentVolumeClaim:
          claimName: globus-connect-data
