apiVersion: v1
kind: Service
metadata:
  name: globus-connect-service
  labels:
    k8s-app: globus-connect
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    k8s-app: globus-connect
