apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: globus-connect
spec:
  serviceName: globus-connect-service
  replicas: 1
  selector:
    matchLabels:
      k8s-app: globus-connect
  minReadySeconds: 10
  template:
    metadata:
      labels:
        k8s-app: globus-connect
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: globus-connect-server
        image: gitlab-registry.nrp-nautilus.io/prp/globus-connect:7f540862
        # image: gitlab-registry.nrp-nautilus.io/prp/globus-connect
        resources:
          # limits can only be 1.2 the requests per NRP rules        
          limits:
            memory: 1.2G
            cpu: 1200m
          requests:
            memory: 1G
            cpu: 1
        ports:
        - containerPort: 80
          name: web
        imagePullPolicy: Always
        args: ['/bin/bash', '-c', 'su - gridftp -c "cd /home/gridftp && chmod 744 /home/gridftp/globus-connect-personal.sh && /home/gridftp/globus-connect-personal.sh"']
        volumeMounts:
            - mountPath: /data
              name: fourcastnet-training-data
      volumes:
      - name: fourcastnet-training-data
        persistentVolumeClaim:
          claimName: fourcastnet-training-data
