apiVersion: v1
kind: Pod
metadata:
  name: jupyterpod-username
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nautilus.io/csu-tide
            operator: Exists
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-L40
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:v1.3
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
        nvidia.com/gpu: 1
      requests:
        cpu: "1"
        memory: 1Gi
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /home/jovyan
      name: jovyan-home
  volumes:
  - name: jovyan-home
    persistentVolumeClaim:
      claimName: jupyter-volume-username
  tolerations:
  - key: nautilus.io/csu-tide
    operator: Exists
    effect: NoSchedule
  - key: nautilus.io/sdsu-fix
    operator: Exists
    effect: NoSchedule    
  