apiVersion: v1
kind: Pod
metadata:
  name: jupyterpod-username
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nautilus.io/csu-tide
            operator: Exists
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-L40
  initContainers:
  - name: take-data-dir-ownership
    image: alpine:3
    command: ["/bin/sh","-c","chown 0:100 /home/jovyan && chmod 775 /home/jovyan"] 
    volumeMounts:
    - mountPath: /home/jovyan
      name: jovyan-home
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:v1.3
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
        nvidia.com/gpu: 1
      requests:
        cpu: "1"
        memory: 1Gi
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /home/jovyan
      name: jovyan-home
    - mountPath: /home/jovyan/shared/fourcastnet
      name: fourcastnet-training-data
    - mountPath: /dev/shm
      name: dshm
  volumes:
  - name: jovyan-home
    persistentVolumeClaim:
      claimName: jupyter-volume-username
  - name: fourcastnet-training-data
    persistentVolumeClaim:
      claimName: fourcastnet-training-data
  - name: dshm
    emptyDir:
      medium: Memory
  tolerations:
  - key: nautilus.io/csu-tide
    operator: Exists
    effect: NoSchedule
  - key: nautilus.io/sdsu-fix
    operator: Exists
    effect: NoSchedule    
  
