apiVersion: batch/v1
kind: Job
metadata:
  name: jupyterpod-username
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/csu-tide
                operator: Exists
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-L40
      restartPolicy: Never
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3
        command: ["/bin/sh","-c","chown 0:100 /home/jovyan && chmod 775 /home/jovyan"] 
        volumeMounts:
        - mountPath: /home/jovyan
          name: jovyan-home
      containers:
      - name: gpu-container
        image: henrylisdsu/climate-lab-notebook:v1.3
        command: ["jupyter", "lab", "--ip='0.0.0.0'"]
        resources:
          # limits can only be 1.2 the requests per NRP rules
          limits:
            cpu: "2.4"
            memory: 9.6G
            nvidia.com/gpu: 1
          requests:
            cpu: "2"
            memory: 8G
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /home/jovyan
          name: jovyan-home
        - mountPath: /home/jovyan/shared/fourcastnet
          name: fourcastnet-training-data
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: jovyan-home
        persistentVolumeClaim:
          claimName: jupyter-volume-username
      - name: fourcastnet-training-data
        persistentVolumeClaim:
          claimName: fourcastnet-training-data
      - name: dshm
        emptyDir:
          medium: Memory
      tolerations:
      - key: nautilus.io/csu-tide
        operator: Exists
        effect: NoSchedule
      - key: nautilus.io/sdsu-fix
        operator: Exists
        effect: NoSchedule
